apiVersion : apps/v1beta1
kind: Deployment
metadata:
 name: a1
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: a1
  spec:
   containers:
   - name: a1
     image: $(ACR.FullName)/$(ACR.ImageName)
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: a1-svc
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
 app: a1

