apiVersion : apps/v1beta1
kind: Deployment
metadata:
 name: a2
spec:
 replicas: 1
 template:
  metadata:
   labels:
     app: a2
  spec:
   containers:
   - name: a2
     image: #{image}#:#{tag}#
     ports:
     - containerPort: 80
   imagePullSecrets:
     - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
 name: a2-svc
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
   app: a2

